# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: python CI staging

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: [self-hosted, Linux, X64, devci]

    strategy:
      matrix:
        python-version: [3.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE
      - uses: actions/checkout@v2

      # Install dependencies
      - name: Install dependencies
        run: pip install -r requirements.txt

      # Run our unit tests
      - name: Run unit tests
        run: flask run --host 0.0.0.0
